defaults:
  - _self_
  - data: wmtask
  - slurm: default

mlp_id: azdses35
neuralode_id: krf14lza
traj_ind: null
extra_time_points: 'all'
Q_weight: 1.0
R_weight: 0.01
# R_weight: 0.1
Qf_weight: 1.0
accuracy_inds: 'all'
use_line_for_ref: false
data_save_dir: ""